### PR TITLE
Update src/soft.json

### PR DESCRIPTION
**Pull request by scko823**

### CODE REVIEW

**Comment by stevenmusumeche** [comment]
Thanks @scko823! Would you mind fixing the spelling errors?  For example `enginner` should be `engineer`.

**Comment by scko823** [comment]
hey @stevenmusumeche I had updated this text 😄

**Comment by stevenmusumeche** [comment]
Thanks @scko823 ! It looks like the JSON has a syntax error and the build is failing:

```
10:08:15 PM: Module parse failed: Unexpected token l in JSON at position 4195 while parsing near '...meetings by saying "let's do this over e...'
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
10:08:15 PM: SyntaxError: Unexpected token l in JSON at position 4195 while parsing near '...meetings by saying "let's do this over e...'
    at JSON.parse (<anonymous>)
```

**Comment by scko823** [comment]
@stevenmusumeche not sure why it was working before with the double quote in json 🤷 anyway I escaped the quote in this PR and the build is back in green

**Comment by stevenmusumeche** [comment]
Thank you!

**Pull request merged**
